spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/digital-library
        #The port of the database(5433) should be adjusted to the DB configuration of the computer it is run on,
        #in my case that is 5433
        username: ${dbUsername}
        password: ${dbPassword}
    jpa:
        database-platform: org.hibernate.dialect.PostgresSQLDialect
        show-sql: 'true'
        hibernate:
            ddl-auto: update
jwt:
    secret-key: ${secretKey}
    #Should be HMACSHA512 encoded to BASE64
server:
    port: '8275'
