spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/digital-library-dev
        #The port of the database(5433) should be adjusted to the DB configuration of the computer it is run on,
        #in my case that is 5433
        username: root
        password: BnwRB4amZE
    jpa:
        database-platform: org.hibernate.dialect.PostgresSQLDialect
        show-sql: 'true'
        hibernate:
            ddl-auto: update
server:
    port: '8061'
