package api;

import java.util.List;

public class Docs {
    private String key;
    private String redirects;
    private String title;
    private String subtitle;
    private String alternative_title;
    private String alternative_subtitle;
    private Integer cover_i;
    private String ebook_access;
    private Integer edition_count;
    private List<String> edition_key;
    private List<String> format;
    private String by_statement;
    private List<String> publish_date;
    private List<String> lccn;
    private List<String> ia;
    private List<String> oclc;
    private List<String> isbn;
    private List<String>  contributor;
    private List<String> publish_place;
    private List<String> publisher;
    private String first_sentence;
    private String author_key;
    private String author_name;
    private List<String> author_alternative_name;
    private List<String> id_goodreads;
    private List<String> id_librarything;
    private List<String> id_dnb;
    private List<String> id_amazon;
    private List<String> id_alibris_id;
    private List<String> id_google;
    private List<String> id_paperback_swap;
    private List<String> id_wikidata;
    private List<String> id_better_world_books;
    private List<String> id_overdrive;
    private String id_canadian_national_library_archive;
    private List<String> subject;
    private List<String> place;
    private String time;
    private List<String> person;
    private Boolean has_fulltext;
    private String title_suggest;
    private List<Integer> publish_year;
    private List<String> language;
    private Integer number_of_pages_median;
    private String ia_count;
    private String publisher_facet;
    private String author_facet;
    private List<String> ia_loaded_id;
    private List<String> ia_box_id;
    private Integer first_publish_year;
    private Integer ratings_average;
    private Integer ratings_sortable;
    private Integer ratings_count;
    private Integer readinglog_count;
    private Integer want_to_read_count;
    private Integer currently_reading_count;
    private Integer already_read_count;
    //Subjects
    private String subject_key;
    private String person_key;
    private String place_key;
    private String time_key;
    //Classifications
    private List<String> lcc;
    private List<String> ddc;
    private String lcc_sort;
    private String ddc_sort;
}
